apiVersion: v1
kind: Service
metadata:
  name: power-horse
  namespace: power-horse
  labels:
    app: power-horse
spec:
  selector:
    app: power-horse
# ClusterIP (default), LoadBalancer (works on cloud), NodePort (most used)
  type: NodePort
  ports:
  - port: 9090 
    targetPort: 9090